add more tips for PR reviews
pixielabs/handbook pull request #3
Opened 2022-01-21 09:13 UTC by hayleypixie

2022-01-21 12:05 UTC, jalada requested changes
This is some great added resolution @hayleypixie, nice one! I may spot some other things once its live on the site but this is a great start.

2022-01-21 12:05 UTC, jalada commented on 03-project-delivery/06-reviews.md
> +  will also benefit.
```suggestion
  can also benefit.
```

2022-01-21 12:05 UTC, jalada commented on 03-project-delivery/06-reviews.md
> +    - "-another strategy- would be better here."
```suggestion
    - bad: "-another strategy- would be better here."
```

2022-01-21 12:05 UTC, jalada commented on 03-project-delivery/06-reviews.md
> +- Check the [handbook](./03-style-guidelines.md) for things that are to do with
```suggestion
- Use the [handbook](./03-style-guidelines.md) as a code style reference.
```

(and delete next line)

2022-01-21 12:05 UTC, jalada commented on 03-project-delivery/06-reviews.md
> +  - We should be on the same page with our code style, if not, prefer to discuss as
```suggestion
  - We should be on the same page with our code style, if not, we should discuss as
```

2022-01-21 12:05 UTC, jalada commented on 03-project-delivery/06-reviews.md
> +  retro & then update the handbook once we have agreement.
```suggestion
  retro and then update the handbook once we have agreement.
```

2022-01-21 12:05 UTC, jalada commented on 03-project-delivery/06-reviews.md
> +  - ::taco::
```suggestion
  - Give an appreciation ::taco:: in #appreciations on Slack!
```

2022-01-21 12:05 UTC, jalada commented on 03-project-delivery/06-reviews.md
> +- React: Are there any missing PropTypes?
Maybe add a link to the proptypes library?

2022-01-21 12:09 UTC, hayleypixie commented
Maybe we can add something about target pull request sizes?

2022-01-21 12:11 UTC, jalada commented
> Maybe we can add something about target pull request sizes?

We actually already have something for that under [Project Delivery Metrics](https://handbook.pixielabs.io/#/02-project-management/05-project-delivery-metrics) but perhaps a link to that somewhere pertinent?

2022-03-31 08:09 UTC, hayleypixie commented
@jalada is this good to merge now?

2022-03-31 08:10 UTC, jalada commented
Do it!

2022-03-31 08:10 UTC, merged