Update 08-writing-tickets.md
pixielabs/handbook pull request #5
Opened 2023-02-03 13:03 UTC by pixie-josh

- Changed description of AC's (imho one of the most important sections)
- Added a dedicated 'Designs/UX' section. From past experience, teams prefer this to be called out as a specific section.
- Changed wording of 'tasks' to 'subtasks' to better align with ClickUp terminology.

2023-02-10 17:53 UTC, jalada requested changes
Just some minor tweaks! Good work.

2023-02-10 17:53 UTC, jalada commented on 02-project-management/08-writing-tickets.md
> +7. Designs/UX
```suggestion
7. Designs and UX
```

2023-02-10 17:53 UTC, jalada commented on 02-project-management/08-writing-tickets.md
> +To make sure we as a team understand the context of the problem we're fixing, what
Let's get all lines wrapped at column 80; it makes for neater markdown files :)

2023-02-10 17:53 UTC, jalada commented on 02-project-management/08-writing-tickets.md
> +kind of user we're solving it for, and what value solcing this problem provides to the customer or business,
```suggestion
kind of user we're solving it for, and what value solving this problem provides to the customer or business, 
```

2023-02-10 17:53 UTC, jalada commented on 02-project-management/08-writing-tickets.md
> +we need a breif description to set the scene for the solution we're providing. This is often
```suggestion
we need a brief description to set the scene for the solution we're providing. This is often 
```

2023-02-10 17:53 UTC, jalada commented on 02-project-management/08-writing-tickets.md
> +Acceptance criteria (AC's) are a set of conditions or requirements that must be
```suggestion
Acceptance criteria (ACs) are a set of conditions or requirements that must be 
```

2023-02-10 17:53 UTC, jalada commented on 02-project-management/08-writing-tickets.md
> +met in order for a ticket to be considered as 'Done'. It helps to clearly define
```suggestion
met in order for a ticket to be considered 'Done'. It helps to clearly define 
```

2023-02-10 17:53 UTC, jalada commented on 02-project-management/08-writing-tickets.md
> +customer’s needs and expectations. Acceptance criteria typically include functional
This is the first smart quote we've got in this file. Check if Docusaurus is automatically giving us smart quotes or not, or what we've done in other files.

2023-02-10 17:53 UTC, jalada commented on 02-project-management/08-writing-tickets.md
> +### Designs/UX
```suggestion
### Designs and UX
```

2023-02-10 17:53 UTC, jalada commented on 02-project-management/08-writing-tickets.md
> +Figma or Miro. Some tickets don't need designs (e.g back-end tickets), but in this case we
I dunno if we want to refer to an anti-pattern like 'back-end tickets' e.g. it implies we don't do vertical slices of functionality in our tickets, which isn't true. Can we think of a better example?

2023-02-10 17:53 UTC, jalada commented on 02-project-management/08-writing-tickets.md
> +AC's however, as AC's are a checklist of the expected functionality, not the steps to
```suggestion
ACs however, as ACs are a checklist of the expected functionality, not the steps to 
```

2023-02-17 11:26 UTC, merged

2023-02-17 11:27 UTC, pixie-josh commented
Merging just to get the page updated with the right content, we can tweak formatting later