Docs/git strategies
pixielabs/handbook pull request #8
Opened 2023-04-03 00:59 UTC by defaye

Add documentation outlining Git best practices and strategies for effective usage. This includes creating a new branch for each feature or bug fix, using descriptive commit messages, using atomic commits, regularly pushing changes to a remote repository, using pull requests for code review and collaboration, reviewing and merging pull requests promptly, and using code review tools or automated tests. Additionally, include strategies for effective Git usage, such as writing good commit messages, creating small, atomic commits, using Git's patch option to pick out atomic commits, treating local commits as mutable, using rebase to restructure commits before pushing, and searching through revision histories.

2023-04-03 08:55 UTC, jalada requested changes
Feedback from a quick pass.

2023-04-03 08:55 UTC, jalada commented on 03-project-delivery/04-tools.md
> +Regularly push changes to a remote repository (e.g., GitHub) to ensure that your work is backed up and accessible to others on the team. This also helps avoid loss of work due to hardware failure or
```suggestion
Regularly push changes to GitHub to ensure that your work is backed up and accessible to others on the team. This also helps avoid loss of work due to hardware failure or other issues.
```

2023-04-03 08:55 UTC, jalada commented on 03-project-delivery/04-tools.md
> +Use atomic commits that are small and focused on a single logical change. An atomic commit is a self-contained unit of work that can be applied or reverted independently of other changes.
Do we really think every commit should be revertible independently? Is that really a thing?

2023-04-03 08:55 UTC, jalada commented on 03-project-delivery/04-tools.md
> +A good revision history is essential for software development. Maintainability is a critical aspect of any software development project, and one of the most critical factors in maintainability is the
I dunno if this paragraph makes sense in a handbook (did ChatGPT write this?)

2023-04-03 08:55 UTC, jalada commented on 03-project-delivery/04-tools.md
> +### Write Good Commit Messages
I dislike title case btw, can we un-titlecase these? I don't think the handbook is title-cased elsewhere

2023-04-03 08:55 UTC, jalada commented on 03-project-delivery/04-tools.md
> +A good commit message should capture both what the change does and why it was made. It should also provide enough context so that anyone reading the message can understand the change. For example, in
This feels like a duplicate of the standard above.

2023-04-03 08:55 UTC, jalada commented on 03-project-delivery/04-tools.md
> +Commits should focus on doing one thing, making them easier to review and understand. For example, instead of combining refactoring and feature work into one commit, separate them into two separate c
Didn't we just have this?

2023-04-03 08:55 UTC, jalada commented on 03-project-delivery/04-tools.md
> +* Use the force wisely: Use `git push --force-with-lease` to force push changes to a remote branch while ensuring that you don't overwrite any changes made by others since your last pull.
I don't know if this is useful for (say) a junior to read.

2023-04-03 08:55 UTC, jalada commented on 03-project-delivery/04-tools.md
> +Use `git rebase -i <commit>` e.g. `git rebase -i HEAD~5` to interactively rebase the commit history and restructure commits, such as changing commit messages, squashing commits, and reordering commit
This probably needs an explanation of what the goal is, e.g. imagine a junior reading it.

2023-04-03 11:56 UTC, defaye commented on 03-project-delivery/04-tools.md
> +A good revision history is essential for software development. Maintainability is a critical aspect of any software development project, and one of the most critical factors in maintainability is the
Yep. This is a inspired by some lessons learned from [A Branch in Time](https://www.youtube.com/watch?v=1NoNTqank_U) (via https://tekin.co.uk/2019/02/a-talk-about-revision-histories)

I wanted to convey the importance of Git commits as an important historical document of a project. Though maybe I'm not understanding what should and shouldn't become content for the handbook 🤔

2023-04-06 07:47 UTC, JonathanAndrews approved these changes
Look's good to me!
One copy change 👍

2023-04-06 07:47 UTC, JonathanAndrews commented on 03-project-delivery/04-tools.md
> +* Don't be afraid to try rebase. You can always use `git rebase --abort` to cancel it if you get unstuck.
Hmmm... how about

```suggestion
* Don't be afraid to try rebase. You can always use `git rebase --abort` to cancel it if you come unstuck.
```

or 
```suggestion
* Don't be afraid to try rebase. You can always use `git rebase --abort` to cancel it if you get yourself in a pickle.
```
?

2023-04-06 07:47 UTC, JonathanAndrews commented on 03-project-delivery/04-tools.md
> +We're not super prescriptive on commit message format but if you want to follow a standardised format, you could use the [Commitlint](https://commitlint.js.org/) style, which uses a standardised form
Meta 🤘
 <img width="1597" alt="Screenshot 2023-04-06 at 08 39 59" src="https://user-images.githubusercontent.com/32128719/230308144-c93cb639-c9bc-4e3c-9746-d8d50d694423.png">

2023-04-24 22:33 UTC, merged